- name: copy repo files to /etc/yum.repos.d
  copy: src="cloudera-manager.repo" dest="/etc/yum.repos.d/cloudera-manager.repo"

- name: install cloudera-manager and related components
  yum: name={{ item }} state=present
  with_items:
    - oracle-j2sdk1.7
    - mysql-connector-java
    - cloudera-manager-agent

- name: db.properties
  copy: src=config.ini dest=/etc/cloudera-scm-agent/config.ini owner=cloudera-scm group=cloudera-scm

- name: copy entrypoint script
  copy: src=entrypoint.sh dest=/entrypoint.sh mode=777
